'use strict';

/**
 * Render a store-backed CRUD handler for a single operation.
 * @param {{
 *   resource: string,
 *   op: 'list'|'detail'|'create'|'update'|'delete',
 *   stubId: string,
 * }} opts
 * @returns {string}
 */
function renderStoreHandler(opts) {
  const resource = String(opts.resource || 'items').replace(/[^a-zA-Z0-9_-]/g, '_');
  const op = opts.op;
  const stubId = opts.stubId || '';
  const colLit = JSON.stringify(resource);

  const bodies = {
    list: `
  const rows = store.collectionList(${colLit});
  return { response: { code: 0, data: rows, message: '' }, httpStatus: 200 };`,
    detail: `
  const pathParts = String(reqPath || '').split('/').filter(Boolean);
  const id = (query && (query.id || query[${colLit} + 'Id'])) || pathParts[pathParts.length - 1];
  const row = store.collectionGet(${colLit}, String(id || ''));
  if (!row) return cases.http_404;
  return { response: { code: 0, data: row, message: '' }, httpStatus: 200 };`,
    create: `
  const payload = body && typeof body === 'object' ? body : {};
  const newId = String(payload.id != null ? payload.id : Date.now());
  const row = store.collectionPut(${colLit}, newId, payload);
  return { response: { code: 0, data: row, message: '' }, httpStatus: 200 };`,
    update: `
  const pathParts = String(reqPath || '').split('/').filter(Boolean);
  const id = (query && (query.id || query[${colLit} + 'Id'])) || pathParts[pathParts.length - 1];
  const existing = store.collectionGet(${colLit}, String(id || ''));
  if (!existing) return cases.http_404;
  const payload = body && typeof body === 'object' ? body : {};
  const row = store.collectionPut(${colLit}, String(id), Object.assign({}, existing, payload, { id: String(id) }));
  return { response: { code: 0, data: row, message: '' }, httpStatus: 200 };`,
    delete: `
  const pathParts = String(reqPath || '').split('/').filter(Boolean);
  const id = (query && (query.id || query[${colLit} + 'Id'])) || pathParts[pathParts.length - 1];
  const ok = store.collectionDelete(${colLit}, String(id || ''));
  if (!ok) return cases.http_404;
  return { response: { code: 0, data: true, message: '' }, httpStatus: 200 };`,
  };

  const body = bodies[op] || bodies.list;

  return `/** Auto-generated by mock-skill — store-backed ${op} — ${stubId}
 * mock-skill:store resource=${resource}
 */
module.exports = ({ method, query, params, body, headers, caseId, store, path: reqPath }) => {
  const cases = {
    empty: { response: { code: 0, data: ${op === 'list' ? '[]' : 'null'}, message: '' }, httpStatus: 200 },
    biz_error: { response: { code: 50000, data: null, message: 'mock business error' }, httpStatus: 200 },
    http_404: { response: { code: 404, data: null, message: 'not found' }, httpStatus: 404 },
    http_500: { response: { code: 500, data: null, message: 'internal server error' }, httpStatus: 500 },
  };
  const idHeader = caseId || (headers && (headers['x-mock-case'] || headers['X-Mock-Case']));
  if (idHeader && idHeader !== 'success' && cases[idHeader]) return cases[idHeader];
${body}
};
`;
}

module.exports = { renderStoreHandler };
