'use strict';

const fs = require('fs');
const path = require('path');
const {
  ensureProjectDirs,
  projectDataDir,
  contractPath,
  mockHandlerPath,
  apiKey,
} = require('../lib/paths');
const { appendAudit } = require('../lib/audit');

function buildDataFields(hints = []) {
  const fields = {};
  for (const h of hints) {
    fields[h] = { type: 'unknown', note: 'inferred from usage' };
  }
  return fields;
}

function buildContract(roleEntry, { taskId, source, resolution }) {
  const id = apiKey(roleEntry);
  const now = new Date().toISOString();
  const historyEntry = {
    taskId: taskId || null,
    role: roleEntry.role,
    at: now,
    action: roleEntry.hasMock ? 'update' : 'create',
  };

  return {
    id,
    method: [roleEntry.method || 'GET'],
    host: roleEntry.host || '_default',
    path: roleEntry.path,
    source: source || 'usage',
    role: roleEntry.role,
    relatedToTask: Boolean(roleEntry.relatedToTask),
    confidence: roleEntry.confidence || 'medium',
    lastTaskId: taskId || null,
    history: [historyEntry],
    resolution: resolution || null,
    request: {
      query: Object.fromEntries(
        (roleEntry.queryHints || []).map((k) => [
          k,
          { type: 'string', required: false, enums: [] },
        ]),
      ),
      body: Object.fromEntries(
        (roleEntry.bodyHints || []).map((k) => [
          k,
          { type: 'unknown', required: false },
        ]),
      ),
      headers: [],
    },
    response: {
      envelope: { code: 'number', data: 'object|null', message: 'string' },
      successCode: 0,
      dataFields: buildDataFields(roleEntry.responseHints),
      bizCodes: [],
    },
    cases: [
      {
        id: 'success',
        when: {},
        response: { code: 0, data: sampleData(roleEntry.responseHints), message: '' },
      },
      {
        id: 'empty',
        when: { header: { 'x-mock-case': 'empty' } },
        response: { code: 0, data: Array.isArray(roleEntry.responseHints) ? [] : {}, message: '' },
      },
      {
        id: 'biz_error',
        when: { header: { 'x-mock-case': 'biz_error' } },
        response: { code: 50000, data: null, message: 'mock business error' },
      },
    ],
    evidences: roleEntry.evidences || [],
  };
}

function sampleData(hints = []) {
  if (!hints.length) return {};
  const o = {};
  for (const h of hints) o[h] = null;
  return o;
}

function renderHandler(contract) {
  const casesJson = JSON.stringify(
    Object.fromEntries(contract.cases.map((c) => [c.id, c.response])),
    null,
    2,
  );
  return `/** Auto-generated by mock-skill — ${contract.id} */
module.exports = ({ method, query, params, body, headers, caseId }) => {
  const cases = ${casesJson};
  const id = caseId || (headers && (headers['x-mock-case'] || headers['X-Mock-Case'])) || 'success';
  if (cases[id]) {
    return cases[id];
  }
  return cases.success || { code: 0, data: {}, message: '' };
};
`;
}

function mergeContract(existing, next, { taskId }) {
  const history = [...(existing.history || []), ...(next.history || [])].slice(-50);
  return {
    ...existing,
    ...next,
    history,
    lastTaskId: taskId || existing.lastTaskId || null,
    request: {
      query: { ...(existing.request?.query || {}), ...(next.request?.query || {}) },
      body: { ...(existing.request?.body || {}), ...(next.request?.body || {}) },
      headers: next.request?.headers || existing.request?.headers || [],
    },
    response: {
      ...existing.response,
      ...next.response,
      dataFields: {
        ...(existing.response?.dataFields || {}),
        ...(next.response?.dataFields || {}),
      },
      bizCodes: next.response?.bizCodes?.length
        ? next.response.bizCodes
        : existing.response?.bizCodes || [],
    },
    cases: next.cases?.length ? next.cases : existing.cases,
    evidences: [
      ...new Set([...(existing.evidences || []), ...(next.evidences || [])]),
    ],
  };
}

function loadExistingContracts(projectSlug) {
  const dir = path.join(projectDataDir(projectSlug), 'contracts');
  const map = new Map();
  if (!fs.existsSync(dir)) return map;
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith('.json')) continue;
    try {
      const c = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
      map.set(c.id, c);
    } catch {
      /* ignore */
    }
  }
  return map;
}

function listExistingMockKeys(projectSlug) {
  const mocksRoot = path.join(projectDataDir(projectSlug), 'mocks');
  const keys = new Set();
  if (!fs.existsSync(mocksRoot)) return keys;

  function walk(dir, host, parts) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        walk(full, host, [...parts, ent.name]);
      } else if (ent.name === 'index.js') {
        const p = '/' + parts.join('/');
        keys.add(`GET ${host}${p}`);
        keys.add(`POST ${host}${p}`);
      }
    }
  }

  for (const hostEnt of fs.readdirSync(mocksRoot, { withFileTypes: true })) {
    if (!hostEnt.isDirectory()) continue;
    walk(path.join(mocksRoot, hostEnt.name), hostEnt.name, []);
  }
  return keys;
}

/**
 * Generate contracts + handlers.
 * @returns {{ generated: number, skipped: number, blocked: string[], reused: number }}
 */
function generateMocks({
  projectSlug,
  roles,
  conflicts = [],
  taskId = null,
  force = false,
  merge = true,
}) {
  ensureProjectDirs(projectSlug);
  const conflictKeys = new Set(
    conflicts.filter((c) => !c.resolution).map((c) => c.apiKey),
  );
  const existing = loadExistingContracts(projectSlug);
  let generated = 0;
  let skipped = 0;
  let reused = 0;
  const blocked = [];

  const rules = [];

  for (const roleEntry of roles) {
    const key = apiKey(roleEntry);

    if (roleEntry.role === 'new' && roleEntry.blocked) {
      blocked.push(key);
      appendAudit(projectSlug, {
        command: 'generate',
        taskId,
        apiKey: key,
        role: 'new',
        summary: 'blocked: missing docs/IO definition',
      });
      skipped++;
      continue;
    }

    if (conflictKeys.has(key) && !force) {
      skipped++;
      appendAudit(projectSlug, {
        command: 'generate',
        taskId,
        apiKey: key,
        role: roleEntry.role,
        summary: 'skipped: unresolved conflict',
      });
      continue;
    }

    const handlerFile = mockHandlerPath(
      projectSlug,
      roleEntry.host || '_default',
      roleEntry.path,
    );
    const hasHandler = fs.existsSync(handlerFile);

    if (
      (roleEntry.role === 'dependency' || roleEntry.role === 'unrelated') &&
      hasHandler &&
      !force
    ) {
      reused++;
      const cPath = contractPath(projectSlug, key);
      if (fs.existsSync(cPath)) {
        const cur = JSON.parse(fs.readFileSync(cPath, 'utf8'));
        cur.lastTaskId = taskId || cur.lastTaskId;
        cur.history = [
          ...(cur.history || []),
          {
            taskId,
            role: roleEntry.role,
            at: new Date().toISOString(),
            action: 'reuse',
          },
        ].slice(-50);
        fs.writeFileSync(cPath, `${JSON.stringify(cur, null, 2)}\n`);
      }
      rules.push({
        id: key,
        host: roleEntry.host === '_default' ? '*' : roleEntry.host,
        pathPrefix: roleEntry.path,
        methods: [roleEntry.method || 'GET'],
      });
      appendAudit(projectSlug, {
        command: 'generate',
        taskId,
        apiKey: key,
        role: roleEntry.role,
        summary: 'reused existing mock',
      });
      continue;
    }

    let contract = buildContract(roleEntry, {
      taskId,
      source: roleEntry.role === 'new' ? 'docs|manual' : 'usage',
    });
    if (merge && existing.has(key)) {
      contract = mergeContract(existing.get(key), contract, { taskId });
    }

    const cPath = contractPath(projectSlug, key);
    fs.mkdirSync(path.dirname(cPath), { recursive: true });
    fs.writeFileSync(cPath, `${JSON.stringify(contract, null, 2)}\n`);

    if (hasHandler && merge && !force && roleEntry.role === 'modify') {
      // keep handler body, only refresh if force — still write if no MANUAL marker
      const prev = fs.readFileSync(handlerFile, 'utf8');
      if (prev.includes('mock-skill:manual')) {
        skipped++;
        appendAudit(projectSlug, {
          command: 'generate',
          taskId,
          apiKey: key,
          role: roleEntry.role,
          summary: 'skipped handler: manual marker',
        });
      } else {
        fs.writeFileSync(handlerFile, renderHandler(contract));
        generated++;
      }
    } else {
      fs.mkdirSync(path.dirname(handlerFile), { recursive: true });
      fs.writeFileSync(handlerFile, renderHandler(contract));
      generated++;
    }

    rules.push({
      id: key,
      host: roleEntry.host === '_default' ? '*' : roleEntry.host,
      pathPrefix: roleEntry.path,
      methods: contract.method || [roleEntry.method || 'GET'],
    });

    appendAudit(projectSlug, {
      command: 'generate',
      taskId,
      apiKey: key,
      role: roleEntry.role,
      summary: hasHandler ? 'updated' : 'created',
    });
  }

  const rulesPath = path.join(projectDataDir(projectSlug), 'proxy-rules.json');
  fs.writeFileSync(rulesPath, `${JSON.stringify(rules, null, 2)}\n`);

  return { generated, skipped, blocked, reused, rulesPath };
}

module.exports = {
  generateMocks,
  buildContract,
  renderHandler,
  loadExistingContracts,
  listExistingMockKeys,
};

if (require.main === module) {
  console.error('Use via mock-skill generate or init');
  process.exit(1);
}
