'use strict';

const fs = require('fs');
const path = require('path');
const {
  ensureProjectDirs,
  projectDataDir,
  contractPath,
  mockHandlerPath,
  apiKey,
  pathDepth,
} = require('../lib/paths');
const { appendAudit } = require('../lib/audit');
const {
  materialize,
  shapeToDataFields,
  buildEnumCases,
} = require('../lib/materialize');

function hintListToObject(hints) {
  if (!hints) return {};
  if (Array.isArray(hints)) {
    return Object.fromEntries(
      hints.map((k) =>
        typeof k === 'string'
          ? [k, { type: 'string', required: false, enums: [] }]
          : [k, k],
      ),
    );
  }
  return hints;
}

function buildContract(roleEntry, { taskId, source, resolution }) {
  const id = apiKey(roleEntry);
  const now = new Date().toISOString();
  const historyEntry = {
    taskId: taskId || null,
    role: roleEntry.role,
    at: now,
    action: roleEntry.hasMock ? 'update' : 'create',
  };

  const shape =
    roleEntry.responseShape ||
    ({
      type: 'object',
      props: Object.fromEntries(
        (roleEntry.responseHints || []).map((h) => [h, { type: 'unknown' }]),
      ),
    });

  const dataSample = materialize(shape);
  const hasData =
    dataSample &&
    typeof dataSample === 'object' &&
    (Array.isArray(dataSample)
      ? dataSample.length > 0
      : Object.keys(dataSample).length > 0);

  const enumCases = buildEnumCases(shape, dataSample);
  const coverage = roleEntry.coverage || {
    request: { keysFound: [], confidence: 'low' },
    response: { pathsFound: [], confidence: 'low' },
    enums: [],
    gaps: ['unknown'],
  };

  const cases = [
    {
      id: 'success',
      when: {},
      response: { code: 0, data: dataSample, message: '' },
    },
    {
      id: 'empty',
      when: { header: { 'x-mock-case': 'empty' } },
      response: {
        code: 0,
        data: Array.isArray(dataSample) ? [] : {},
        message: '',
      },
    },
    {
      id: 'biz_error',
      when: { header: { 'x-mock-case': 'biz_error' } },
      response: { code: 50000, data: null, message: 'mock business error' },
    },
    ...enumCases,
  ];

  return {
    id,
    method: [roleEntry.method || 'GET'],
    host: roleEntry.host || '_default',
    path: roleEntry.path,
    source: source || 'usage',
    role: roleEntry.role,
    relatedToTask: Boolean(roleEntry.relatedToTask),
    confidence: roleEntry.confidence || 'medium',
    lastTaskId: taskId || null,
    history: [historyEntry],
    resolution: resolution || null,
    request: {
      query: hintListToObject(
        roleEntry.queryHints?.length
          ? roleEntry.queryHints
          : coverage.request?.keysFound || [],
      ),
      body: hintListToObject(roleEntry.bodyHints || []),
      headers: [],
    },
    response: {
      envelope: { code: 'number', data: 'object|null', message: 'string' },
      successCode: 0,
      dataFields: shapeToDataFields(shape),
      bizCodes: [],
      source: hasData ? 'usage' : 'empty',
      shape,
    },
    cases,
    coverage,
    evidences: roleEntry.evidences || [],
    exportHint: roleEntry.exportHint || null,
  };
}

function renderHandler(contract) {
  const casesJson = JSON.stringify(
    Object.fromEntries(contract.cases.map((c) => [c.id, c.response])),
    null,
    2,
  );
  return `/** Auto-generated by mock-skill — ${contract.id} */
module.exports = ({ method, query, params, body, headers, caseId }) => {
  const cases = ${casesJson};
  const id = caseId || (headers && (headers['x-mock-case'] || headers['X-Mock-Case'])) || 'success';
  if (cases[id]) {
    return cases[id];
  }
  return cases.success || { code: 0, data: {}, message: '' };
};
`;
}

function mergeContract(existing, next, { taskId }) {
  const history = [...(existing.history || []), ...(next.history || [])].slice(
    -50,
  );
  // Prefer richer data sample
  const nextData = next.cases?.find((c) => c.id === 'success')?.response?.data;
  const prevData = existing.cases?.find((c) => c.id === 'success')?.response
    ?.data;
  const nextRich =
    nextData &&
    typeof nextData === 'object' &&
    Object.keys(nextData).length > 0;
  const prevRich =
    prevData &&
    typeof prevData === 'object' &&
    Object.keys(prevData).length > 0;

  const cases =
    nextRich || !prevRich
      ? next.cases
      : mergeCasesPreserve(existing.cases, next.cases);

  return {
    ...existing,
    ...next,
    history,
    lastTaskId: taskId || existing.lastTaskId || null,
    request: {
      query: { ...(existing.request?.query || {}), ...(next.request?.query || {}) },
      body: { ...(existing.request?.body || {}), ...(next.request?.body || {}) },
      headers: next.request?.headers || existing.request?.headers || [],
    },
    response: {
      ...existing.response,
      ...next.response,
      dataFields: {
        ...(existing.response?.dataFields || {}),
        ...(next.response?.dataFields || {}),
      },
      shape: nextRich
        ? next.response?.shape
        : existing.response?.shape || next.response?.shape,
    },
    cases,
    coverage: next.coverage || existing.coverage,
    evidences: [
      ...new Set([...(existing.evidences || []), ...(next.evidences || [])]),
    ],
  };
}

function mergeCasesPreserve(prev = [], next = []) {
  const map = new Map(prev.map((c) => [c.id, c]));
  for (const c of next) {
    if (!map.has(c.id) || c.id !== 'success') map.set(c.id, c);
    else if (
      c.id === 'success' &&
      Object.keys(c.response?.data || {}).length >
        Object.keys(map.get('success').response?.data || {}).length
    ) {
      map.set(c.id, c);
    }
  }
  return [...map.values()];
}

function loadExistingContracts(projectSlug) {
  const dir = path.join(projectDataDir(projectSlug), 'contracts');
  const map = new Map();
  if (!fs.existsSync(dir)) return map;
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith('.json')) continue;
    try {
      const c = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
      map.set(c.id, c);
    } catch {
      /* ignore */
    }
  }
  return map;
}

function listExistingMockKeys(projectSlug) {
  const mocksRoot = path.join(projectDataDir(projectSlug), 'mocks');
  const keys = new Set();
  if (!fs.existsSync(mocksRoot)) return keys;

  function walkDir(dir, host, parts) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        walkDir(full, host, [...parts, ent.name]);
      } else if (ent.name === 'index.js') {
        const p = '/' + parts.join('/');
        keys.add(`GET ${host}${p}`);
        keys.add(`POST ${host}${p}`);
      }
    }
  }

  for (const hostEnt of fs.readdirSync(mocksRoot, { withFileTypes: true })) {
    if (!hostEnt.isDirectory()) continue;
    walkDir(path.join(mocksRoot, hostEnt.name), hostEnt.name, []);
  }
  return keys;
}

/** Remove gateway-only mocks (path depth <= 1) left by old infer */
function cleanupGatewayOnlyMocks(projectSlug) {
  const mocksRoot = path.join(projectDataDir(projectSlug), 'mocks');
  const contractsDir = path.join(projectDataDir(projectSlug), 'contracts');
  let removed = 0;
  if (!fs.existsSync(mocksRoot)) return removed;

  function rmHandler(host, parts) {
    const p = '/' + parts.join('/');
    if (pathDepth(p) > 1) return;
    const handler = path.join(mocksRoot, host, ...parts, 'index.js');
    if (fs.existsSync(handler)) {
      fs.unlinkSync(handler);
      removed++;
      // remove empty dirs
      try {
        fs.rmdirSync(path.join(mocksRoot, host, ...parts));
      } catch {
        /* ignore */
      }
    }
    // remove matching contracts
    if (fs.existsSync(contractsDir)) {
      for (const f of fs.readdirSync(contractsDir)) {
        if (!f.endsWith('.json')) continue;
        try {
          const c = JSON.parse(
            fs.readFileSync(path.join(contractsDir, f), 'utf8'),
          );
          if (c.host === host && c.path === p && pathDepth(p) <= 1) {
            fs.unlinkSync(path.join(contractsDir, f));
          }
        } catch {
          /* ignore */
        }
      }
    }
  }

  function walkDir(dir, host, parts) {
    if (!fs.existsSync(dir)) return;
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        walkDir(full, host, [...parts, ent.name]);
        // after children, if this is depth-1 leaf with index already removed
      } else if (ent.name === 'index.js') {
        rmHandler(host, parts);
      }
    }
  }

  for (const hostEnt of fs.readdirSync(mocksRoot, { withFileTypes: true })) {
    if (!hostEnt.isDirectory()) continue;
    walkDir(path.join(mocksRoot, hostEnt.name), hostEnt.name, []);
  }
  return removed;
}

function generateMocks({
  projectSlug,
  roles,
  conflicts = [],
  taskId = null,
  force = false,
  merge = true,
}) {
  ensureProjectDirs(projectSlug);
  const removedGateway = cleanupGatewayOnlyMocks(projectSlug);

  const conflictKeys = new Set(
    conflicts.filter((c) => !c.resolution).map((c) => c.apiKey),
  );
  const existing = loadExistingContracts(projectSlug);
  let generated = 0;
  let skipped = 0;
  let reused = 0;
  let usageBackedCount = 0;
  let emptyDataCount = 0;
  let enumBackedCount = 0;
  const gapApis = [];
  const blocked = [];
  const rules = [];

  // Skip roles that are still gateway-only
  const filteredRoles = roles.filter((r) => {
    const p = r.path || '';
    return pathDepth(p) > 1;
  });

  for (const roleEntry of filteredRoles) {
    const key = apiKey(roleEntry);

    if (roleEntry.role === 'new' && roleEntry.blocked) {
      blocked.push(key);
      skipped++;
      continue;
    }
    if (conflictKeys.has(key) && !force) {
      skipped++;
      continue;
    }

    const handlerFile = mockHandlerPath(
      projectSlug,
      roleEntry.host || '_default',
      roleEntry.path,
    );
    const hasHandler = fs.existsSync(handlerFile);

    if (
      (roleEntry.role === 'dependency' || roleEntry.role === 'unrelated') &&
      hasHandler &&
      !force
    ) {
      // Still refresh contract IO if usage-backed is richer
      let contract = buildContract(roleEntry, {
        taskId,
        source: 'usage',
      });
      if (merge && existing.has(key)) {
        contract = mergeContract(existing.get(key), contract, { taskId });
      }
      fs.writeFileSync(
        contractPath(projectSlug, key),
        `${JSON.stringify(contract, null, 2)}\n`,
      );
      if (contract.response?.source === 'usage') usageBackedCount++;
      else emptyDataCount++;
      if (contract.coverage?.enums?.length) enumBackedCount++;
      if (contract.coverage?.gaps?.length) {
        gapApis.push({ id: key, gaps: contract.coverage.gaps });
      }
      reused++;
      rules.push({
        id: key,
        host: roleEntry.host === '_default' ? '*' : roleEntry.host,
        pathPrefix: roleEntry.path,
        methods: [roleEntry.method || 'GET'],
      });
      continue;
    }

    let contract = buildContract(roleEntry, {
      taskId,
      source: roleEntry.role === 'new' ? 'docs|manual' : 'usage',
    });
    if (merge && existing.has(key)) {
      contract = mergeContract(existing.get(key), contract, { taskId });
    }

    if (contract.response?.source === 'usage') usageBackedCount++;
    else emptyDataCount++;
    if (contract.coverage?.enums?.length) enumBackedCount++;
    if (contract.coverage?.gaps?.length) {
      gapApis.push({ id: key, gaps: contract.coverage.gaps });
    }

    const cPath = contractPath(projectSlug, key);
    fs.mkdirSync(path.dirname(cPath), { recursive: true });
    fs.writeFileSync(cPath, `${JSON.stringify(contract, null, 2)}\n`);

    if (hasHandler && merge && !force && roleEntry.role === 'modify') {
      const prev = fs.readFileSync(handlerFile, 'utf8');
      if (prev.includes('mock-skill:manual')) {
        skipped++;
      } else {
        fs.writeFileSync(handlerFile, renderHandler(contract));
        generated++;
      }
    } else {
      fs.mkdirSync(path.dirname(handlerFile), { recursive: true });
      fs.writeFileSync(handlerFile, renderHandler(contract));
      generated++;
    }

    rules.push({
      id: key,
      host: roleEntry.host === '_default' ? '*' : roleEntry.host,
      pathPrefix: roleEntry.path,
      methods: contract.method || [roleEntry.method || 'GET'],
    });

    appendAudit(projectSlug, {
      command: 'generate',
      taskId,
      apiKey: key,
      role: roleEntry.role,
      summary: hasHandler ? 'updated' : 'created',
    });
  }

  const rulesPath = path.join(projectDataDir(projectSlug), 'proxy-rules.json');
  fs.writeFileSync(rulesPath, `${JSON.stringify(rules, null, 2)}\n`);

  return {
    generated,
    skipped,
    blocked,
    reused,
    rulesPath,
    removedGateway,
    usageBackedCount,
    emptyDataCount,
    enumBackedCount,
    gapApis,
    gatewayFilteredRoles: roles.length - filteredRoles.length,
  };
}

module.exports = {
  generateMocks,
  buildContract,
  renderHandler,
  loadExistingContracts,
  listExistingMockKeys,
  cleanupGatewayOnlyMocks,
};

if (require.main === module) {
  console.error('Use via mock-skill generate or init');
  process.exit(1);
}
